zone_1:
  name: zone_1
  shapefile: examples\zone_1\zone_1.shp
  id_col: zone_1_id
zone_2:
  name: zone_2
  shapefile: examples\zone_2\zone_2.shp
  id_col: zone_2_id
cache_path: examples\test_cache
method: test
tolerance: 0.98
rounding: True
filter_slithers: True
lower_zoning:
  name: lower
  shapefile: examples\lower_zone\lower_zone.shp
  id_col: lower_id
  weight_data: example\lower_zone\weight.csv
  data_col: weight
  weight_id_col: lower_id